plugins:
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: "module"
  project: "./tsconfig.json"
env:
  commonjs: true
  node: true
  es6: true
rules:
  # Possible errors
  for-direction: 2
  getter-return: 2
  no-async-promise-executor: 1
  no-compare-neg-zero: 1
  no-cond-assign: 2
  no-constant-condition: 2
  no-control-regex: 2
  no-debugger: 2
  no-duplicate-case: 2
  no-empty-character-class: 2
  no-ex-assign: 2
  no-extra-parens: 0
  no-extra-semi: 2
  no-inner-declarations: 1
  no-invalid-regexp: 2
  no-irregular-whitespace: 2
  no-misleading-character-class: 2
  no-prototype-builtins: 2
  no-regex-spaces: 2
  no-sparse-arrays: 2
  no-template-curly-in-string: 2
  no-unreachable: 2
  no-unsafe-finally: 2
  no-unsafe-negation: 2
  require-atomic-updates: 2
  use-isnan: 2

  # Best Practices
  accessor-pairs: 2
  class-methods-use-this: 1
  # complexity: 2
  curly:
    - 2
    - all
  default-case: 2
  dot-location:
    - 2
    - property
  # dot-notation:
  #   - 2
  #   - allowKeywords: false
  eqeqeq: 2
  guard-for-in: 2
  no-alert: 2
  no-caller: 2
  no-case-declarations: 2
  no-div-regex: 2
  # no-else-return:
  #   - 2
  #   - allowElseIf: true
  # no-empty-function: 2
  no-empty-pattern: 2
  no-eq-null: 2
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-label: 2
  no-fallthrough: 2
  no-floating-decimal: 2
  no-global-assign: 2
  no-implicit-coercion:
    - 2
    - allow:
      - "!!"
  no-implied-eval: 2
  # no-invalid-this: 2
  no-iterator: 2
  no-labels: 2
  no-lone-blocks: 2
  no-loop-func: 2
  no-multi-spaces: 2
  no-multi-str: 2
  no-new: 2
  no-new-func: 2
  no-new-wrappers: 2
  no-octal: 2
  no-octal-escape: 2
  no-param-reassign: 2
  no-proto: 2
  no-redeclare: 2
  no-return-assign: 2
  no-return-await: 2
  no-script-url: 2
  no-self-assign: 2
  no-self-compare: 2
  no-throw-literal: 2
  no-unmodified-loop-condition: 2
  no-unused-expressions: 2
  no-unused-labels: 2
  no-useless-call: 2
  no-useless-catch: 2
  no-useless-concat: 2
  no-useless-escape: 2
  no-useless-return: 2
  no-void: 2
  no-warning-comments: 1
  no-with: 2
  prefer-named-capture-group: 1
  prefer-promise-reject-errors: 2
  radix: 2
  require-await: 2
  require-unicode-regexp: 2
  wrap-iife: 2
  yoda: 2

  # Variables
  init-declarations: 2
  no-delete-var: 2
  no-label-var: 2
  no-shadow: 2
  no-shadow-restricted-names: 2
  no-undef: 2

  # Stylistic Issues
  array-bracket-spacing: 2
  array-element-newline:
    - 2
    - consistent
  block-spacing: 2
  brace-style:
    - 2
    - stroustrup
  # capitalized-comments: 2
  comma-dangle:
    - 2
    - always-multiline
  comma-spacing: 2
  comma-style: 2
  computed-property-spacing: 2
  eol-last: 2
  func-call-spacing: 0
  func-name-matching: 2
  func-names: 2
  func-style:
    - 2
    - declaration
    - allowArrowFunctions: true
  function-call-argument-newline:
    - 2
    - consistent
  function-paren-newline:
    - 2
    - consistent
  indent: 0
  jsx-quotes: 2
  key-spacing: 2
  keyword-spacing: 2
  line-comment-position: 2
  lines-around-comment:
    - 2
    - beforeBlockComment: true
  # lines-around-comment":
  #   - 2
  #   - beforeBlockComment: true
  #     allowBlockStart: true
  #     beforeLineComment: true
  lines-between-class-members: 2
  max-len:
    - 2
    - code: 100
      ignoreComments: true
      ignoreTemplateLiterals: true
      ignorePattern: "^import |^export \\{(.*?)\\}|^ \\* "
  max-statements-per-line: [2, { max: 2 }]
  multiline-ternary:
    - 2
    - always-multiline
  new-parens: 2
  newline-per-chained-call:
    - 2
    - ignoreChainWithDepth: 2
  no-array-constructor: 2
  no-bitwise: 2
  no-continue: 2
  no-inline-comments: 2
  no-lonely-if: 2
  no-mixed-operators:
    - 2
    - groups:
      - ["&", "|", "^", "~", "<<", ">>", ">>>"]
      - ["==", "!=", "===", "!==", ">", ">=", "<", "<="]
      - ["&&", "||"]
      - ["in", "instanceof"]
      allowSamePrecedence: true
  no-mixed-spaces-and-tabs: 2
  no-multi-assign: 2
  no-multiple-empty-lines: 2
  no-negated-condition: 2
  no-new-object: 2
  no-tabs: 2
  no-trailing-spaces: 2
  no-unneeded-ternary: 2
  nonblock-statement-body-position: 2
  # object-curly-newline:
  #   - 2
  #   - multiline: true
  object-curly-spacing:
    - 2
    - always
  operator-assignment: 2
  operator-linebreak:
    - 2
    - before
    - overrides:
        "=": after
  padded-blocks:
    - 2
    - blocks: never
      classes: never
      switches: never
  padding-line-between-statements:
    - 2
    - blankLine: always
      prev: "*"
      next: return
  prefer-object-spread: 2
  quote-props:
    - 2
    - consistent
  quotes:
    - 2
    - double
    - avoidEscape: true
      allowTemplateLiterals: true
  semi: 0
  semi-spacing: 2
  semi-style: 2
  space-before-blocks: 2
  space-before-function-paren: 2
  space-in-parens: 2
  space-infix-ops:
    - 2
    - int32Hint: true
  space-unary-ops: 2
  spaced-comment: 2
  switch-colon-spacing: 2
  template-tag-spacing:
    - 2
    - always

  # ECMAScript 6
  arrow-body-style: 2
  arrow-parens:
    - 2
    - as-needed
  arrow-spacing: 2
  constructor-super: 2
  generator-star-spacing:
    - 2
    - after
  no-class-assign: 2
  no-new-symbol: 2
  no-this-before-super: 2
  no-useless-computed-key: 2
  no-useless-constructor: 2
  no-useless-rename: 2
  no-var: 2
  object-shorthand: 2
  prefer-arrow-callback: 2
  prefer-const: 2
  prefer-destructuring:
    - 2
    - object: true
      array: false
  prefer-numeric-literals: 2
  prefer-rest-params: 2
  prefer-spread: 2
  prefer-template: 2
  require-yield: 2
  rest-spread-spacing: 2
  # sort-imports:
  #   - 2
  #   - ignoreCase: true
  #     ignoreMemberSort: true
  symbol-description: 2
  template-curly-spacing: 2
  yield-star-spacing:
    - 2
    - after

  # TypeScript
  "@typescript-eslint/adjacent-overload-signatures": 2
  "@typescript-eslint/array-type": 2
  "@typescript-eslint/await-thenable": 2
  # "@typescript-eslint/class-name-casing": 2
  "@typescript-eslint/consistent-type-assertions": 2
  "@typescript-eslint/func-call-spacing":
    - 2
    - always
    - allowNewlines: true
  # "@typescript-eslint/indent":
  #   - 2
  #   - 2
  #   - flatTernaryExpressions: true
  "@typescript-eslint/interface-name-prefix": 2
  "@typescript-eslint/no-extra-parens":
    - 1
    - functions
  "@typescript-eslint/no-floating-promises": 2
  "@typescript-eslint/no-for-in-array": 2
  "@typescript-eslint/no-inferrable-types": 2
  "@typescript-eslint/no-misused-new": 2
  "@typescript-eslint/no-misused-promises": 2
  "@typescript-eslint/no-this-alias": 2
  "@typescript-eslint/no-unnecessary-type-arguments": 2
  "@typescript-eslint/no-unnecessary-type-assertion": 2
  "@typescript-eslint/prefer-for-of": 2
  "@typescript-eslint/prefer-includes": 2
  "@typescript-eslint/prefer-readonly": 2
  "@typescript-eslint/promise-function-async": 2
  # "@typescript-eslint/quotes": 2
  "@typescript-eslint/require-array-sort-compare": 2
  "@typescript-eslint/require-await": 2
  "@typescript-eslint/restrict-plus-operands": 2
  # "@typescript-eslint/semi":
  #   - 2
  #   - never
  "@typescript-eslint/strict-boolean-expressions": 2
  "@typescript-eslint/triple-slash-reference": 2
  "@typescript-eslint/type-annotation-spacing": 2
  # "@typescript-eslint/unbound-method": 2
  "@typescript-eslint/unified-signatures": 2
